### ISSUE TITLE
Add support for boostrap v2.3.2

### ISSUE THREAD

**Issue by reptildarat** [daveaglick/FluentBootstrap#26]
Hi,

Can you add support for old bootstrap (version 2.3.2) ?

Many thanks.

**Comment by daveaglick** [comment]
As much as I would love to add legacy support (especially for 2.3.2, which I know a lot of folks are still using), there are just too many differences between the 2.X and 3.X Bootstrap versions to make it a straightforward change. I made a conscious decision to focus on 3.X versions when writing FluentBootstrap and I just don't have the time to go back and re-write the helpers for 2.X. This is especially true with 4.X around the corner, which I do intend to support.

That said, I'd be more than happy to merge a PR if someone else wants to take it on... :)
