### ISSUE TITLE
SetIcon() on ButtonDropdown()

### ISSUE THREAD

**Issue by patrikmor** [daveaglick/FluentBootstrap#28]
When using SetIcon() on ButtonDropdown() the resulted span with glyphicon is rendered to \<ul\> tag instead of \<button\> tag as expected.

**Comment by daveaglick** [comment]
Thanks for reporting this. Sure enough, I can reproduce and have a failing test. Look for a fix shortly.

**Comment by daveaglick** [comment]
This is now fixed in the develop branch. I'll merge with master and release a new NuGet version momentarily.
