### ISSUE TITLE
FluentBootstrap RadioFor() does not check the radio button if the field value is equal to the radio value, contrast to Razor RadioButtonFor() behavior.

### ISSUE THREAD

**Issue by ryanelian** [daveaglick/FluentBootstrap#30]
The controller

![1](https://cloud.githubusercontent.com/assets/8892187/7711782/0cd990e4-fe97-11e4-99ed-8759cf8795f5.PNG)

The view

![2](https://cloud.githubusercontent.com/assets/8892187/7711794/31a73430-fe97-11e4-90b5-152fc33c87b9.PNG)

The result

![3](https://cloud.githubusercontent.com/assets/8892187/7711799/399247fc-fe97-11e4-91f6-504f557b8514.PNG)

Also, I would like to give you an applause for `@Html.Bootstrap().SelectFor()` accepting options passed as `IEnumerable` of `KeyValuePair <string,string>`. Do you think you can do the same for Radio? (Accepts `IEnumerable` of `string` and/or `KeyValuePair<string,string>` and generates the radio list appropriately)

Thank you in advance and keep up the good work!

**Comment by daveaglick** [comment]
Thanks - another very good catch. It looks like neither the radio or select are picking up the selected state. It'll probably be next week at the earliest that I get a chance to dig into this, but I'll hopefully be able to get this and the similar select issue as well as your previous one sorted out soon. Once they're all wrapped up I'll push a new release to NuGet.

Keep them coming!

**Comment by daveaglick** [comment]
This is now resolved in the `develop` branch. I've also captured the request for better extensions for making sequences of form elements as issue #34
