### ISSUE TITLE
FluentBootstrap SelectFor() does not select the option which value is equal to the property value, contrast to Razor DropDownListFor() behavior.

### ISSUE THREAD

**Issue by ryanelian** [daveaglick/FluentBootstrap#31]
The Controller

![1](https://cloud.githubusercontent.com/assets/8892187/7712268/90b437e0-fe9a-11e4-96b7-7ea79ca8f89d.PNG)

The View

![2](https://cloud.githubusercontent.com/assets/8892187/7712272/94de803c-fe9a-11e4-803e-5c0aefb7c9f3.PNG)

The Result

![3](https://cloud.githubusercontent.com/assets/8892187/7712280/9a1ecafc-fe9a-11e4-9111-96834d040ad1.PNG)

Thank you in advance and keep up the good work!

**Comment by daveaglick** [comment]
This is now fixed in `develop`. It was a little more complicated than the fix for `RadioFor` because the select list could potentially have options added after creation using `AddOptions`. Ended up storing the model value (if any) in the `Select` component for use in subsequent `AddOptions` calls.
