### ISSUE TITLE
Add Forms.Form functionality to NavbarForm's ComponentBuilder

### ISSUE THREAD

**Issue by tishin** [daveaglick/FluentBootstrap#32]
Form methods (e.g., SetAction, HideValidationSummary) don't seem to work with NavbarForm's ComponentBuilder.
Thank you.

**Comment by daveaglick** [comment]
Thanks for the bug report. This is now fixed in the `develop` branch and should be pushed out to the `master` branch and to NuGet in the next couple days once I wrap up a few other changes.
