### ISSUE TITLE
InputFor() generates incorrect name value for nested entity

### ISSUE THREAD

**Issue by frankvaneykelen** [daveaglick/FluentBootstrap#44]
This is how the built-in HTML helpers deal with nested entities:

Razor:

    @Html.LabelFor(model => model.Album.Price)
    @Html.EditorFor(model => model.Album.Price)

HTML:

    <label for="Album_Price">Price</label>
    <input class="text-box single-line" id="Album_Price" name="Album.Price" type="text" value="" />

Please note that  the dot has been replaced by an underscore __for the 'id' and 'for' attributes only__.

FluentBootstrap handles it differently (incorrectly):

Razor:

     @Html.Bootstrap().InputFor(model => model.Album.Price)

HTML:

     <div class="form-group">
          <label for="Album_Price" class="control-label col-xs-4">Price</label>
          <div class="col-xs-3">
             <input type="text" name="Album_Price" id="Album_Price" class="form-control">
      </div>
 </div>

Please note that the dot has been replaced by an underscore __for the 'name' attribute too__. 

I would expect the name of the markup generated by the FluentBootstrap helper to be the same. This also breaks my model binding.

I have changed GetControlName to fix this is my project. It now does this:

    return helper.GetConfig().HtmlHelper.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName(expressionText);

I also added these lines to Tag.OnStart():

    if (string.Equals(attribute.Key, "id", StringComparison.Ordinal) || string.Equals(attribute.Key, "for", StringComparison.Ordinal))
        {
            encoded = TagBuilder.CreateSanitizedId(encoded);
        }

**Comment by daveaglick** [comment]
Great catch, thanks. And especially thanks for including a fix :) I'll get this patched up and a new version up on NuGet ASAP (most likely later today).

**Comment by frankvaneykelen** [comment]
Great! Please make sure that to add CreateSanitizedId()'s everywhere it's needed - I only fixed for my use case, but there may be others!

**Comment by daveaglick** [comment]
Can you confirm which version of FluentBootstrap you're using? It looks like this may have been fixed in 3.3.5.0. It looks like I'm currently getting the correct output from the tests:

![2015-09-25_13h13_41](https://cloud.githubusercontent.com/assets/1020407/10107222/ac0815be-6387-11e5-9c91-a2f58ad2f3a1.png)

**Comment by JoeMighty** [comment]
I've not been able to replicate it either.

**Comment by frankvaneykelen** [comment]
@daveaglick version: 3.3.4.4. I'll go and try the latest version.

**Comment by frankvaneykelen** [comment]
I can confirm that this is fixed in 3.3.5.1. Thanks for your help.

**Comment by daveaglick** [comment]
Excellent - glad it's working for you now. Just let me know if you run into any other problems.
