### ISSUE TITLE
InputFor does not support DisplayFormat

### ISSUE THREAD

**Issue by frankvaneykelen** [daveaglick/FluentBootstrap#48]
I have this attribute on my model:

    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

To make this work for InputFor in FluentBootstrap.Mvc v 3.3.5.1 I had to add/change the next two lines in 
 `public static ComponentBuilder<MvcBootstrapConfig<TModel>, Input> InputFor<TComponent, TModel, TValue>()` in FluentBootstrap.Mvc\Forms\MvcFormExtensions.cs:

    string valueFormat = metadata.EditFormatString;
    return helper.Input(name, label, metadata.Model, valueFormat, inputType);

**Comment by daveaglick** [comment]
Thanks for the feedback. Change made in develop - hopefully getting a release to NuGet out today.

**Comment by frankvaneykelen** [comment]
Great, thanks!
