### ISSUE TITLE
Navbar Fixed

### ISSUE THREAD

**Issue by gmreburn** [daveaglick/FluentBootstrap#52]
The bootstrap navbar component can be fixed to the top or the bottom of the viewport with the class navbar-fixed-top and navbar-fixed-bottom.

Add support for fixed navbars.

See: [http://getbootstrap.com/components/#navbar-fixed-top](http://getbootstrap.com/components/#navbar-fixed-top)

**Comment by daveaglick** [comment]
See the `.SetPosition(NavbarPosition)` fluent method. Specifically, take a look at this example from the tests: https://github.com/daveaglick/FluentBootstrap/blob/develop/FluentBootstrap.Tests.Web/Views/Tests/Navbars.cshtml#L27

Does that do what you need or is it missing something?

**Comment by gmreburn** [comment]
That is what I was looking for. Thank you.

**Comment by daveaglick** [comment]
:+1:
