### ISSUE TITLE
Extra form-group div getting added at the end of forms

### ISSUE THREAD

**Issue by gulsharan** [daveaglick/FluentBootstrap#56]
The code below yields a form tag with an unexpected form-group div appended at the end. Am I missing something?

![sampleform](https://cloud.githubusercontent.com/assets/577631/15380488/914e6ae2-1d3c-11e6-988f-d06f7e11da62.png)

![extraformgroup](https://cloud.githubusercontent.com/assets/577631/15380455/3cbd3012-1d3c-11e6-8ce1-e581a120425f.png)

**Comment by Noer024** [comment]
I beleive that is the validation summary automatically added to the end of a form. You should be able to use .HideValidationSummary() to hide it.

**Comment by gulsharan** [comment]
@Noer024 This is exactly what I was looking for. Thanks a lot!

**Comment by daveaglick** [comment]
Totally forgot about this issue, thanks @Noer024!
